
import { Geist, Geist_Mono,Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import ThemeProvider from "./components/ThemeProvider";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>

        <main className="mx-auto px-4 py-4">
        <Navbar/>
        {children}
        </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
